name: CI
on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 7
          run_install: false
      - name: Install deps
        run: pnpm install
      - name: Run test
        run: pnpm run test:ci
